-- 코드를 입력하세요
# JOIN 풀이
SELECT A.FLAVOR
FROM FIRST_HALF A LEFT JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER > 3000 && B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC

# // SELECT FLAVOR FROM FIRST_HALF WHERE TOTAL_ORDER > 3000 AND FLAVOR IN (SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based') ORDER BY TOTAL_ORDER DESC;